// 🌍 بيانات الدول مع كود البلد (ISO) - مصنفة بأسماء الدول ومترجمة لـ 6 لغات
export const nationalitiesData: Record<string, { value: string; label: string; iso: string }[]> = {
    ar: [
        { value: 'Syria', label: 'سوريا', iso: 'sy' },
        { value: 'Egypt', label: 'مصر', iso: 'eg' },
        { value: 'Saudi Arabia', label: 'السعودية', iso: 'sa' },
        { value: 'Lebanon', label: 'لبنان', iso: 'lb' },
        { value: 'Jordan', label: 'الأردن', iso: 'jo' },
        { value: 'UAE', label: 'الإمارات', iso: 'ae' },
        { value: 'Morocco', label: 'المغرب', iso: 'ma' },
        { value: 'Algeria', label: 'الجزائر', iso: 'dz' },
        { value: 'Tunisia', label: 'تunes', iso: 'tn' },
        { value: 'Iraq', label: 'العراق', iso: 'iq' },
        { value: 'Kuwait', label: 'الكويت', iso: 'kw' },
        { value: 'Oman', label: 'عمان', iso: 'om' },
        { value: 'Qatar', label: 'قطر', iso: 'qa' },
        { value: 'Bahrain', label: 'البحرين', iso: 'bh' },
        { value: 'Yemen', label: 'اليمن', iso: 'ye' },
        { value: 'Palestine', label: 'فلسطين', iso: 'ps' },
        { value: 'Libya', label: 'ليبيا', iso: 'ly' },
        { value: 'Sudan', label: 'السودان', iso: 'sd' },
        { value: 'Mauritania', label: 'موريتانيا', iso: 'mr' },
        { value: 'Somalia', label: 'الصومال', iso: 'so' },
        { value: 'Djibouti', label: 'جيبوتي', iso: 'dj' },
        { value: 'Comoros', label: 'جزر القمر', iso: 'km' },
        { value: 'Japan', label: 'اليابان', iso: 'jp' },
        { value: 'China', label: 'الصين', iso: 'cn' },
        { value: 'South Korea', label: 'كوريا الجنوبية', iso: 'kr' },
        { value: 'North Korea', label: 'كوريا الشمالية', iso: 'kp' },
        { value: 'France', label: 'فرنسا', iso: 'fr' },
        { value: 'Spain', label: 'إسبانيا', iso: 'es' },
        { value: 'USA', label: 'أمريكا', iso: 'us' },
        { value: 'United Kingdom', label: 'بريطانيا', iso: 'gb' },
        { value: 'Canada', label: 'كندا', iso: 'ca' },
        { value: 'Germany', label: 'ألمانيا', iso: 'de' },
        { value: 'Italy', label: 'إيطاليا', iso: 'it' },
        { value: 'Turkey', label: 'تركيا', iso: 'tr' },
        { value: 'Iran', label: 'إيران', iso: 'ir' },
        { value: 'India', label: 'الهند', iso: 'in' },
        { value: 'Pakistan', label: 'باكستان', iso: 'pk' },
        { value: 'Bangladesh', label: 'بنجلاديش', iso: 'bd' },
        { value: 'Indonesia', label: 'إندونيسيا', iso: 'id' },
        { value: 'Malaysia', label: 'ماليزيا', iso: 'my' },
        { value: 'Singapore', label: 'سنغافورة', iso: 'sg' },
        { value: 'Philippines', label: 'الفلبين', iso: 'ph' },
        { value: 'Thailand', label: 'تايلاند', iso: 'th' },
        { value: 'Vietnam', label: 'فيتنام', iso: 'vn' },
        { value: 'Russia', label: 'روسيا', iso: 'ru' },
        { value: 'Ukraine', label: 'أوكرانيا', iso: 'ua' },
        { value: 'Brazil', label: 'البرازيل', iso: 'br' },
        { value: 'Argentina', label: 'الأرجنتين', iso: 'ar' },
        { value: 'Mexico', label: 'المكسيك', iso: 'mx' },
        { value: 'Colombia', label: 'كولومبيا', iso: 'co' },
        { value: 'Chile', label: 'تشيلي', iso: 'cl' },
        { value: 'Peru', label: 'بيرو', iso: 'pe' },
        { value: 'Australia', label: 'أستراليا', iso: 'au' },
        { value: 'New Zealand', label: 'نيوزيلندا', iso: 'nz' },
        { value: 'South Africa', label: 'جنوب أفريقيا', iso: 'za' },
        { value: 'Nigeria', label: 'نيجيريا', iso: 'ng' },
        { value: 'Kenya', label: 'كينيا', iso: 'ke' },
        { value: 'Ethiopia', label: 'إثيوبيا', iso: 'et' },
        { value: 'Greece', label: 'اليونان', iso: 'gr' },
        { value: 'Netherlands', label: 'هولندا', iso: 'nl' },
        { value: 'Belgium', label: 'بلجيكا', iso: 'be' },
        { value: 'Switzerland', label: 'سويسرا', iso: 'ch' },
        { value: 'Austria', label: 'النمسا', iso: 'at' },
        { value: 'Sweden', label: 'السويد', iso: 'se' },
        { value: 'Norway', label: 'النرويج', iso: 'no' },
        { value: 'Denmark', label: 'الدنمارك', iso: 'dk' },
        { value: 'Finland', label: 'فنلندا', iso: 'fi' },
        { value: 'Ireland', label: 'أيرلندا', iso: 'ie' },
        { value: 'Portugal', label: 'البرتغال', iso: 'pt' },
        { value: 'Poland', label: 'بولندا', iso: 'pl' }
    ],
    en: [
        { value: 'Syria', label: 'Syria', iso: 'sy' },
        { value: 'Egypt', label: 'Egypt', iso: 'eg' },
        { value: 'Saudi Arabia', label: 'Saudi Arabia', iso: 'sa' },
        { value: 'Lebanon', label: 'Lebanon', iso: 'lb' },
        { value: 'Jordan', label: 'Jordan', iso: 'jo' },
        { value: 'UAE', label: 'UAE', iso: 'ae' },
        { value: 'Morocco', label: 'Morocco', iso: 'ma' },
        { value: 'Algeria', label: 'Algeria', iso: 'dz' },
        { value: 'Tunisia', label: 'Tunisia', iso: 'tn' },
        { value: 'Iraq', label: 'Iraq', iso: 'iq' },
        { value: 'Kuwait', label: 'Kuwait', iso: 'kw' },
        { value: 'Oman', label: 'Oman', iso: 'om' },
        { value: 'Qatar', label: 'Qatar', iso: 'qa' },
        { value: 'Bahrain', label: 'Bahrain', iso: 'bh' },
        { value: 'Yemen', label: 'Yemen', iso: 'ye' },
        { value: 'Palestine', label: 'Palestine', iso: 'ps' },
        { value: 'Libya', label: 'Libya', iso: 'ly' },
        { value: 'Sudan', label: 'Sudan', iso: 'sd' },
        { value: 'Mauritania', label: 'Mauritania', iso: 'mr' },
        { value: 'Somalia', label: 'Somalia', iso: 'so' },
        { value: 'Djibouti', label: 'Djibouti', iso: 'dj' },
        { value: 'Comoros', label: 'Comoros', iso: 'km' },
        { value: 'Japan', label: 'Japan', iso: 'jp' },
        { value: 'China', label: 'China', iso: 'cn' },
        { value: 'South Korea', label: 'South Korea', iso: 'kr' },
        { value: 'North Korea', label: 'North Korea', iso: 'kp' },
        { value: 'France', label: 'France', iso: 'fr' },
        { value: 'Spain', label: 'Spain', iso: 'es' },
        { value: 'USA', label: 'USA', iso: 'us' },
        { value: 'United Kingdom', label: 'United Kingdom', iso: 'gb' },
        { value: 'Canada', label: 'Canada', iso: 'ca' },
        { value: 'Germany', label: 'Germany', iso: 'de' },
        { value: 'Italy', label: 'Italy', iso: 'it' },
        { value: 'Turkey', label: 'Turkey', iso: 'tr' },
        { value: 'Iran', label: 'Iran', iso: 'ir' },
        { value: 'India', label: 'India', iso: 'in' },
        { value: 'Pakistan', label: 'Pakistan', iso: 'pk' },
        { value: 'Bangladesh', label: 'Bangladesh', iso: 'bd' },
        { value: 'Indonesia', label: 'Indonesia', iso: 'id' },
        { value: 'Malaysia', label: 'Malaysia', iso: 'my' },
        { value: 'Singapore', label: 'Singapore', iso: 'sg' },
        { value: 'Philippines', label: 'Philippines', iso: 'ph' },
        { value: 'Thailand', label: 'Thailand', iso: 'th' },
        { value: 'Vietnam', label: 'Vietnam', iso: 'vn' },
        { value: 'Russia', label: 'Russia', iso: 'ru' },
        { value: 'Ukraine', label: 'Ukraine', iso: 'ua' },
        { value: 'Brazil', label: 'Brazil', iso: 'br' },
        { value: 'Argentina', label: 'Argentina', iso: 'ar' },
        { value: 'Mexico', label: 'Mexico', iso: 'mx' },
        { value: 'Colombia', label: 'Colombia', iso: 'co' },
        { value: 'Chile', label: 'Chile', iso: 'cl' },
        { value: 'Peru', label: 'Peru', iso: 'pe' },
        { value: 'Australia', label: 'Australia', iso: 'au' },
        { value: 'New Zealand', label: 'New Zealand', iso: 'nz' },
        { value: 'South Africa', label: 'South Africa', iso: 'za' },
        { value: 'Nigeria', label: 'Nigeria', iso: 'ng' },
        { value: 'Kenya', label: 'Kenya', iso: 'ke' },
        { value: 'Ethiopia', label: 'Ethiopia', iso: 'et' },
        { value: 'Greece', label: 'Greece', iso: 'gr' },
        { value: 'Netherlands', label: 'Netherlands', iso: 'nl' },
        { value: 'Belgium', label: 'Belgium', iso: 'be' },
        { value: 'Switzerland', label: 'Switzerland', iso: 'ch' },
        { value: 'Austria', label: 'Austria', iso: 'at' },
        { value: 'Sweden', label: 'Sweden', iso: 'se' },
        { value: 'Norway', label: 'Norway', iso: 'no' },
        { value: 'Denmark', label: 'Denmark', iso: 'dk' },
        { value: 'Finland', label: 'Finland', iso: 'fi' },
        { value: 'Ireland', label: 'Ireland', iso: 'ie' },
        { value: 'Portugal', label: 'Portugal', iso: 'pt' },
        { value: 'Poland', label: 'Poland', iso: 'pl' }
    ],
    fr: [
        { value: 'Syria', label: 'Syrie', iso: 'sy' },
        { value: 'Egypt', label: 'Égypte', iso: 'eg' },
        { value: 'Saudi Arabia', label: 'Arabie saoudite', iso: 'sa' },
        { value: 'Lebanon', label: 'Liban', iso: 'lb' },
        { value: 'Jordan', label: 'Jordanie', iso: 'jo' },
        { value: 'UAE', label: 'Émirats arabes unis', iso: 'ae' },
        { value: 'Morocco', label: 'Maroc', iso: 'ma' },
        { value: 'Algeria', label: 'Algérie', iso: 'dz' },
        { value: 'Tunisia', label: 'Tunisie', iso: 'tn' },
        { value: 'Iraq', label: 'Irak', iso: 'iq' },
        { value: 'Kuwait', label: 'Koweït', iso: 'kw' },
        { value: 'Oman', label: 'Oman', iso: 'om' },
        { value: 'Qatar', label: 'Qatar', iso: 'qa' },
        { value: 'Bahrain', label: 'Bahreïn', iso: 'bh' },
        { value: 'Yemen', label: 'Yémen', iso: 'ye' },
        { value: 'Palestine', label: 'Palestine', iso: 'ps' },
        { value: 'Libya', label: 'Libye', iso: 'ly' },
        { value: 'Sudan', label: 'Soudan', iso: 'sd' },
        { value: 'Mauritania', label: 'Mauritanie', iso: 'mr' },
        { value: 'Somalia', label: 'Somalie', iso: 'so' },
        { value: 'Djibouti', label: 'Djibouti', iso: 'dj' },
        { value: 'Comoros', label: 'Comores', iso: 'km' },
        { value: 'Japan', label: 'Japon', iso: 'jp' },
        { value: 'China', label: 'Chine', iso: 'cn' },
        { value: 'South Korea', label: 'Corée du Sud', iso: 'kr' },
        { value: 'North Korea', label: 'Corée du Nord', iso: 'kp' },
        { value: 'France', label: 'France', iso: 'fr' },
        { value: 'Spain', label: 'Espagne', iso: 'es' },
        { value: 'USA', label: 'États-Unis', iso: 'us' },
        { value: 'United Kingdom', label: 'Royaume-Uni', iso: 'gb' },
        { value: 'Canada', label: 'Canada', iso: 'ca' },
        { value: 'Germany', label: 'Allemagne', iso: 'de' },
        { value: 'Italy', label: 'Italie', iso: 'it' },
        { value: 'Turkey', label: 'Turquie', iso: 'tr' },
        { value: 'Iran', label: 'Iran', iso: 'ir' },
        { value: 'India', label: 'Inde', iso: 'in' },
        { value: 'Pakistan', label: 'Pakistan', iso: 'pk' },
        { value: 'Bangladesh', label: 'Bangladesh', iso: 'bd' },
        { value: 'Indonesia', label: 'Indonésie', iso: 'id' },
        { value: 'Malaysia', label: 'Malaisie', iso: 'my' },
        { value: 'Singapore', label: 'Singapour', iso: 'sg' },
        { value: 'Philippines', label: 'Philippines', iso: 'ph' },
        { value: 'Thailand', label: 'Thaïlande', iso: 'th' },
        { value: 'Vietnam', label: 'Viêt Nam', iso: 'vn' },
        { value: 'Russia', label: 'Russie', iso: 'ru' },
        { value: 'Ukraine', label: 'Ukraine', iso: 'ua' },
        { value: 'Brazil', label: 'Brésil', iso: 'br' },
        { value: 'Argentina', label: 'Argentine', iso: 'ar' },
        { value: 'Mexico', label: 'Mexique', iso: 'mx' },
        { value: 'Colombia', label: 'Colombie', iso: 'co' },
        { value: 'Chile', label: 'Chili', iso: 'cl' },
        { value: 'Peru', label: 'Pérou', iso: 'pe' },
        { value: 'Australia', label: 'Australie', iso: 'au' },
        { value: 'New Zealand', label: 'Nouvelle-Zélande', iso: 'nz' },
        { value: 'South Africa', label: 'Afrique du Sud', iso: 'za' },
        { value: 'Nigeria', label: 'Nigéria', iso: 'ng' },
        { value: 'Kenya', label: 'Kenya', iso: 'ke' },
        { value: 'Ethiopia', label: 'Éthiopie', iso: 'et' },
        { value: 'Greece', label: 'Grèce', iso: 'gr' },
        { value: 'Netherlands', label: 'Pays-Bas', iso: 'nl' },
        { value: 'Belgium', label: 'Belgique', iso: 'be' },
        { value: 'Switzerland', label: 'Suisse', iso: 'ch' },
        { value: 'Austria', label: 'Autriche', iso: 'at' },
        { value: 'Sweden', label: 'Suède', iso: 'se' },
        { value: 'Norway', label: 'Norvège', iso: 'no' },
        { value: 'Denmark', label: 'Danemark', iso: 'dk' },
        { value: 'Finland', label: 'Finlande', iso: 'fi' },
        { value: 'Ireland', label: 'Irlande', iso: 'ie' },
        { value: 'Portugal', label: 'Portugal', iso: 'pt' },
        { value: 'Poland', label: 'Pologne', iso: 'pl' }
    ],
    es: [
        { value: 'Syria', label: 'Siria', iso: 'sy' },
        { value: 'Egypt', label: 'Egipto', iso: 'eg' },
        { value: 'Saudi Arabia', label: 'Arabia Saudita', iso: 'sa' },
        { value: 'Lebanon', label: 'Líbano', iso: 'lb' },
        { value: 'Jordan', label: 'Jordania', iso: 'jo' },
        { value: 'UAE', label: 'Emiratos Árabes Unidos', iso: 'ae' },
        { value: 'Morocco', label: 'Marruecos', iso: 'ma' },
        { value: 'Algeria', label: 'Argelia', iso: 'dz' },
        { value: 'Tunisia', label: 'Túnez', iso: 'tn' },
        { value: 'Iraq', label: 'Irak', iso: 'iq' },
        { value: 'Kuwait', label: 'Kuwait', iso: 'kw' },
        { value: 'Oman', label: 'Omán', iso: 'om' },
        { value: 'Qatar', label: 'Catar', iso: 'qa' },
        { value: 'Bahrain', label: 'Baréin', iso: 'bh' },
        { value: 'Yemen', label: 'Yemen', iso: 'ye' },
        { value: 'Palestine', label: 'Palestina', iso: 'ps' },
        { value: 'Libya', label: 'Libia', iso: 'ly' },
        { value: 'Sudan', label: 'Sudán', iso: 'sd' },
        { value: 'Mauritania', label: 'Mauritania', iso: 'mr' },
        { value: 'Somalia', label: 'Somalia', iso: 'so' },
        { value: 'Djibouti', label: 'Yibuti', iso: 'dj' },
        { value: 'Comoros', label: 'Comoras', iso: 'km' },
        { value: 'Japan', label: 'Japón', iso: 'jp' },
        { value: 'China', label: 'China', iso: 'cn' },
        { value: 'South Korea', label: 'Corea del Sur', iso: 'kr' },
        { value: 'North Korea', label: 'Corea del Nord', iso: 'kp' },
        { value: 'France', label: 'Francia', iso: 'fr' },
        { value: 'Spain', label: 'España', iso: 'es' },
        { value: 'USA', label: 'Estados Unidos', iso: 'us' },
        { value: 'United Kingdom', label: 'Reino Unido', iso: 'gb' },
        { value: 'Canada', label: 'Canadá', iso: 'ca' },
        { value: 'Germany', label: 'Alemania', iso: 'de' },
        { value: 'Italy', label: 'Italia', iso: 'it' },
        { value: 'Turkey', label: 'Turquía', iso: 'tr' },
        { value: 'Iran', label: 'Irán', iso: 'ir' },
        { value: 'India', label: 'India', iso: 'in' },
        { value: 'Pakistan', label: 'Pakistán', iso: 'pk' },
        { value: 'Bangladesh', label: 'Bangladés', iso: 'bd' },
        { value: 'Indonesia', label: 'Indonesia', iso: 'id' },
        { value: 'Malaysia', label: 'Malasia', iso: 'my' },
        { value: 'Singapore', label: 'Singapur', iso: 'sg' },
        { value: 'Philippines', label: 'Filipinas', iso: 'ph' },
        { value: 'Thailand', label: 'Tailandia', iso: 'th' },
        { value: 'Vietnam', label: 'Vietnam', iso: 'vn' },
        { value: 'Russia', label: 'Rusia', iso: 'ru' },
        { value: 'Ukraine', label: 'Ucrania', iso: 'ua' },
        { value: 'Brazil', label: 'Brasil', iso: 'br' },
        { value: 'Argentina', label: 'Argentina', iso: 'ar' },
        { value: 'Mexico', label: 'México', iso: 'mx' },
        { value: 'Colombia', label: 'Colombia', iso: 'co' },
        { value: 'Chile', label: 'Chile', iso: 'cl' },
        { value: 'Peru', label: 'Perú', iso: 'pe' },
        { value: 'Australia', label: 'Australia', iso: 'au' },
        { value: 'New Zealand', label: 'Nueva Zelanda', iso: 'nz' },
        { value: 'South Africa', label: 'Sudáfrica', iso: 'za' },
        { value: 'Nigeria', label: 'Nigeria', iso: 'ng' },
        { value: 'Kenya', label: 'Kenia', iso: 'ke' },
        { value: 'Ethiopia', label: 'Etiopía', iso: 'et' },
        { value: 'Greece', label: 'Grecia', iso: 'gr' },
        { value: 'Netherlands', label: 'Países Bajos', iso: 'nl' },
        { value: 'Belgium', label: 'Bélgica', iso: 'be' },
        { value: 'Switzerland', label: 'Suiza', iso: 'ch' },
        { value: 'Austria', label: 'Austria', iso: 'at' },
        { value: 'Sweden', label: 'Suecia', iso: 'se' },
        { value: 'Norway', label: 'Noruega', iso: 'no' },
        { value: 'Denmark', label: 'Dinamarca', iso: 'dk' },
        { value: 'Finland', label: 'Finlandia', iso: 'fi' },
        { value: 'Ireland', label: 'Irlanda', iso: 'ie' },
        { value: 'Portugal', label: 'Portugal', iso: 'pt' },
        { value: 'Poland', label: 'Polonia', iso: 'pl' }
    ],
    zh: [
        { value: 'Syria', label: '叙利亚', iso: 'sy' },
        { value: 'Egypt', label: '埃及', iso: 'eg' },
        { value: 'Saudi Arabia', label: '沙特阿拉伯', iso: 'sa' },
        { value: 'Lebanon', label: '黎巴嫩', iso: 'lb' },
        { value: 'Jordan', label: '约旦', iso: 'jo' },
        { value: 'UAE', label: '阿联酋', iso: 'ae' },
        { value: 'Morocco', label: '摩洛哥', iso: 'ma' },
        { value: 'Algeria', label: '阿尔及利亚', iso: 'dz' },
        { value: 'Tunisia', label: '突尼斯', iso: 'tn' },
        { value: 'Iraq', label: '伊拉克', iso: 'iq' },
        { value: 'Kuwait', label: '科威特', iso: 'kw' },
        { value: 'Oman', label: '阿曼', iso: 'om' },
        { value: 'Qatar', label: '卡塔尔', iso: 'qa' },
        { value: 'Bahrain', label: '巴林', iso: 'bh' },
        { value: 'Yemen', label: '也门', iso: 'ye' },
        { value: 'Palestine', label: '巴勒斯坦', iso: 'ps' },
        { value: 'Libya', label: '利比亚', iso: 'ly' },
        { value: 'Sudan', label: '苏丹', iso: 'sd' },
        { value: 'Mauritania', label: '毛里塔尼亚', iso: 'mr' },
        { value: 'Somalia', label: '索马里', iso: 'so' },
        { value: 'Djibouti', label: '吉布提', iso: 'dj' },
        { value: 'Comoros', label: '科摩罗', iso: 'km' },
        { value: 'Japan', label: '日本', iso: 'jp' },
        { value: 'China', label: '中国', iso: 'cn' },
        { value: 'South Korea', label: '韩国', iso: 'kr' },
        { value: 'North Korea', label: '朝鲜', iso: 'kp' },
        { value: 'France', label: '法国', iso: 'fr' },
        { value: 'Spain', label: '西班牙', iso: 'es' },
        { value: 'USA', label: '美国', iso: 'us' },
        { value: 'United Kingdom', label: '英国', iso: 'gb' },
        { value: 'Canada', label: '加拿大', iso: 'ca' },
        { value: 'Germany', label: '德国', iso: 'de' },
        { value: 'Italy', label: '意大利', iso: 'it' },
        { value: 'Turkey', label: '土耳其', iso: 'tr' },
        { value: 'Iran', label: '伊朗', iso: 'ir' },
        { value: 'India', label: '印度', iso: 'in' },
        { value: 'Pakistan', label: '巴基斯坦', iso: 'pk' },
        { value: 'Bangladesh', label: '孟加拉国', iso: 'bd' },
        { value: 'Indonesia', label: '印度尼西亚', iso: 'id' },
        { value: 'Malaysia', label: '马来西亚', iso: 'my' },
        { value: 'Singapore', label: '新加坡', iso: 'sg' },
        { value: 'Philippines', label: '菲律宾', iso: 'ph' },
        { value: 'Thailand', label: '泰国', iso: 'th' },
        { value: 'Vietnam', label: '越南', iso: 'vn' },
        { value: 'Russia', label: '俄罗斯', iso: 'ru' },
        { value: 'Ukraine', label: '乌克兰', iso: 'ua' },
        { value: 'Brazil', label: '巴西', iso: 'br' },
        { value: 'Argentina', label: '阿根廷', iso: 'ar' },
        { value: 'Mexico', label: '墨西哥', iso: 'mx' },
        { value: 'Colombia', label: '哥伦比亚', iso: 'co' },
        { value: 'Chile', label: '智利', iso: 'cl' },
        { value: 'Peru', label: '秘鲁', iso: 'pe' },
        { value: 'Australia', label: '澳大利亚', iso: 'au' },
        { value: 'New Zealand', label: '新西兰', iso: 'nz' },
        { value: 'South Africa', label: '南非', iso: 'za' },
        { value: 'Nigeria', label: '尼日利亚', iso: 'ng' },
        { value: 'Kenya', label: '肯尼亚', iso: 'ke' },
        { value: 'Ethiopia', label: '埃塞俄比亚', iso: 'et' },
        { value: 'Greece', label: '希腊', iso: 'gr' },
        { value: 'Netherlands', label: '荷兰', iso: 'nl' },
        { value: 'Belgium', label: '比利时', iso: 'be' },
        { value: 'Switzerland', label: '瑞士', iso: 'ch' },
        { value: 'Austria', label: '奥地利', iso: 'at' },
        { value: 'Sweden', label: '瑞典', iso: 'se' },
        { value: 'Norway', label: '挪威', iso: 'no' },
        { value: 'Denmark', label: '丹麦', iso: 'dk' },
        { value: 'Finland', label: '芬兰', iso: 'fi' },
        { value: 'Ireland', label: '爱尔兰', iso: 'ie' },
        { value: 'Portugal', label: '葡萄牙', iso: 'pt' },
        { value: 'Poland', label: '波兰', iso: 'pl' }
    ],
    ja: [
        { value: 'Syria', label: 'シリア', iso: 'sy' },
        { value: 'Egypt', label: 'エジプト', iso: 'eg' },
        { value: 'Saudi Arabia', label: 'サウジアラビア', iso: 'sa' },
        { value: 'Lebanon', label: 'レバノン', iso: 'lb' },
        { value: 'Jordan', label: 'ヨルダン', iso: 'jo' },
        { value: 'UAE', label: 'アラブ首長国連邦', iso: 'ae' },
        { value: 'Morocco', label: 'モロッコ', iso: 'ma' },
        { value: 'Algeria', label: 'アルジェリア', iso: 'dz' },
        { value: 'Tunisia', label: 'チュニジア', iso: 'tn' },
        { value: 'Iraq', label: 'イラク', iso: 'iq' },
        { value: 'Kuwait', label: 'クウェート', iso: 'kw' },
        { value: 'Oman', label: 'オマーン', iso: 'om' },
        { value: 'Qatar', label: 'カタール', iso: 'qa' },
        { value: 'Bahrain', label: 'バーレーン', iso: 'bh' },
        { value: 'Yemen', label: 'イエメン', iso: 'ye' },
        { value: 'Palestine', label: 'パレスチナ', iso: 'ps' },
        { value: 'Libya', label: 'リビア', iso: 'ly' },
        { value: 'Sudan', label: 'スーダン', iso: 'sd' },
        { value: 'Mauritania', label: 'モーリタニア', iso: 'mr' },
        { value: 'Somalia', label: 'ソマリア', iso: 'so' },
        { value: 'Djibouti', label: 'ジブチ', iso: 'dj' },
        { value: 'Comoros', label: 'コモロ', iso: 'km' },
        { value: 'Japan', label: '日本', iso: 'jp' },
        { value: 'China', label: '中国', iso: 'cn' },
        { value: 'South Korea', label: '韓国', iso: 'kr' },
        { value: 'North Korea', label: '北朝鮮', iso: 'kp' },
        { value: 'France', label: 'フランス', iso: 'fr' },
        { value: 'Spain', label: 'スペイン', iso: 'es' },
        { value: 'USA', label: 'アメリカ', iso: 'us' },
        { value: 'United Kingdom', label: 'イギリス', iso: 'gb' },
        { value: 'Canada', label: 'カナダ', iso: 'ca' },
        { value: 'Germany', label: 'ドイツ', iso: 'de' },
        { value: 'Italy', label: 'イタリア', iso: 'it' },
        { value: 'Turkey', label: 'トルコ', iso: 'tr' },
        { value: 'Iran', label: 'イラン', iso: 'ir' },
        { value: 'India', label: 'インド', iso: 'in' },
        { value: 'Pakistan', label: 'パキスタン', iso: 'pk' },
        { value: 'Bangladesh', label: 'バングラデシュ', iso: 'bd' },
        { value: 'Indonesia', label: 'インドネシア', iso: 'id' },
        { value: 'Malaysia', label: 'マレーシア', iso: 'my' },
        { value: 'Singapore', label: 'シンガポール', iso: 'sg' },
        { value: 'Philippines', label: 'フィリピン', iso: 'ph' },
        { value: 'Thailand', label: 'タイ', iso: 'th' },
        { value: 'Vietnam', label: 'ベトナム', iso: 'vn' },
        { value: 'Russia', label: 'ロシア', iso: 'ru' },
        { value: 'Ukraine', label: 'ウクライナ', iso: 'ua' },
        { value: 'Brazil', label: 'ブラジル', iso: 'br' },
        { value: 'Argentina', label: 'アルゼンチン', iso: 'ar' },
        { value: 'Mexico', label: 'メキシコ', iso: 'mx' },
        { value: 'Colombia', label: 'コロンビア', iso: 'co' },
        { value: 'Chile', label: 'チリ', iso: 'cl' },
        { value: 'Peru', label: 'ペルー', iso: 'pe' },
        { value: 'Australia', label: 'オーストラリア', iso: 'au' },
        { value: 'New Zealand', label: 'ニュージーランド', iso: 'nz' },
        { value: 'South Africa', label: '南アフリカ', iso: 'za' },
        { value: 'Nigeria', label: 'ナイジェリア', iso: 'ng' },
        { value: 'Kenya', label: 'ケニア', iso: 'ke' },
        { value: 'Ethiopia', label: 'エチオピア', iso: 'et' },
        { value: 'Greece', label: 'ギリシャ', iso: 'gr' },
        { value: 'Netherlands', label: 'オランダ', iso: 'nl' },
        { value: 'Belgium', label: 'ベルギー', iso: 'be' },
        { value: 'Switzerland', label: 'スイス', iso: 'ch' },
        { value: 'Austria', label: 'オーストリア', iso: 'at' },
        { value: 'Sweden', label: 'スウェーデン', iso: 'se' },
        { value: 'Norway', label: 'ノルウェー', iso: 'no' },
        { value: 'Denmark', label: 'デンマーク', iso: 'dk' },
        { value: 'Finland', label: 'フィンランド', iso: 'fi' },
        { value: 'Ireland', label: 'アイルランド', iso: 'ie' },
        { value: 'Portugal', label: 'ポルトガル', iso: 'pt' },
        { value: 'Poland', label: 'ポーランド', iso: 'pl' }
    ]
};