version: '3.8'

services:
  # واجهة React
  frontend:
    build: ./front
    ports:
      - "80:80" # التعديل هنا ليعمل الموقع مباشرة على المنفذ الافتراضي
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/Japanese-Academy-Backend:/var/www/Japanese-Academy-Backend:ro # ملفات الأكاديمية
      - /run/php:/run/php
    depends_on:
      - backend

  # خلفية Laravel
  backend:
    build: ./back
    volumes:
      - ./back:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db

  # قاعدة البيانات
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: your_secure_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: